SELECT * FROM ALUGUEL_ARMARIO;
SELECT * FROM ARMARIO;

SELECT * FROM ALUNO WHERE NOME LIKE 'vivian%';

SELECT * FROM USUARIO;

INSERT INTO USUARIO (ID_USUARIO, ID_LKP_TIPO_USUARIO, NOME, USERNAME, PW) VALUES (1,1,'ADMINISTRADOR DA SILVA', 'ADMIN', MD5('123mudar'));

SELECT SYSDATE() FROM DUAL
DASELECT * FROM ALUGUEL_ARMARIO WHERE DATA_DEVOLUCAO = DATE(NOW());


DELETE FROM USUARIO;
DELETE FROM ALUGUEL_ARMARIO WHERE ID_ALUGUEL_ARMARIO = 14;
SELECT A.CHAVE, AL.NOME, AA.DATA_DEVOLUCAO
FROM ALUGUEL_ARMARIO AA
INNER JOIN ALUNO AL ON AL.ID_ALUNO = AA.ID_ALUNO
INNER JOIN ARMARIO A ON A.ID_ARMARIO = AA.ID_ARMARIO
ORDER BY A.CHAVE;



DROP TRIGGER ALOCAR_ARMARIO_TRG
DROP TRIGGER DESALOCAR_ARMARIO_TRG;