
SELECT * FROM ALUGUEL_ARMARIO;
SELECT * FROM USUARIO;
SELECT * FROM ALUNO;
SELECT * FROM ARMARIO;

--INSERCAO DE USUARIO ADMINISTRADOR
INSERT INTO USUARIO  (ID_USUARIO, ID_LKP_TIPO_USUARIO, NOME) VALUES (1, 1, 'FERNANDO PUCCI');

--INSERCAO DE ALUNOS
INSERT INTO ALUNO (ID_ALUNO, NOME, SEXO, TELEFONE, EMAIL) VALUES(1, 'ZEH DA SILVA', 'M','99999999999','teste@teste.com');
INSERT INTO ALUNO (ID_ALUNO,NOME, SEXO, TELEFONE, EMAIL) VALUES(2, 'PEDRO DA SILVA', 'M','99999999999','teste@teste.com');

--INSERCAO DE ARMARIOS
INSERT INTO ARMARIO (ID_ARMARIO, CHAVE, DESCRICAO) VALUES (1, 91999999,'ARMARIO 1'); 
INSERT INTO ARMARIO (ID_ARMARIO, CHAVE, DESCRICAO) VALUES (2, 92999999,'ARMARIO 2');
INSERT INTO ARMARIO (ID_ARMARIO, CHAVE, DESCRICAO) VALUES (3, 93999999,'ARMARIO 3');

--INSERCAO DE ALOCACAO DE ARMARIO
INSERT INTO ALUGUEL_ARMARIO(ID_ARMARIO,ID_ALUNO,ID_USUARIO_RESPONSAVEL,DATA_ALUGUEL) VALUES (1,1,1,SYSDATE());
INSERT INTO ALUGUEL_ARMARIO(ID_ARMARIO,ID_ALUNO,ID_USUARIO_RESPONSAVEL,DATA_ALUGUEL) VALUES (2,2,1,SYSDATE());



--ATUALIZACAO DE DESALOCACAO DE ARMARIO
UPDATE ALUGUEL_ARMARIO 
SET DATA_DEVOLUCAO = DATE_ADD(SYSDATE(), INTERVAL 2 DAY)
  , FLG_DEVOLVIDO = 1
WHERE ID_ALUGUEL_ARMARIO = 1;



DELETE FROM ALUGUEL_ARMARIO;
UPDATE ARMARIO SET FLG_OCUPADO = 0, FLG_ATIVO = 1;
--DELETE FROM ARMARIO;
--DELETE FROM ALUNO;
--DELETE FROM USUARIO;
--DELETE FROM ARMARIO;
--DELETE FROM ALUGUEL_ARMARIO;