/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etefgarcia.armarios.view;

import br.com.etefgarcia.armarios.action.ConfigInicialViewAction;
import br.com.etefgarcia.armarios.controller.ConfigController;
import br.com.etefgarcia.armarios.model.Config;
import br.com.etefgarcia.armarios.util.constantes.telas.ConstantesTelas;
import br.com.etefgarcia.armarios.util.Mensagens;
import java.io.IOException;

/**
 *
 * @author fernando-pucci
 */
public class ConfigInicialView extends javax.swing.JFrame {

    private ConfigController configController;
    private ConfigInicialViewAction configInicialViewAction;

    /**
     * Creates new form ConfigInicialView
     *
     */
    public ConfigInicialView() throws IOException, ClassNotFoundException {
        initComponents();
        inicializar();
        inicializarDados();

    }

    private void inicializar() throws IOException, ClassNotFoundException {

        this.configController = new ConfigController(this);
        this.configInicialViewAction = new ConfigInicialViewAction(configController);
        //
        removeListeners();
        adicionaListeners();

    }

    private void inicializarDados() {

        Config c = configController.getConfig();

        jTextFieldDatabase.setText(c.getBanco());
        jTextFieldHost.setText(c.getHost());
        jTextFieldPorta.setText(c.getServidorPorta());
        jTextFieldUser.setText(c.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonTestarConfiguracao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldHost = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPorta = new javax.swing.JTextField();
        jTextFieldDatabase = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(ConstantesTelas.TITULO_JANELA_PRINCIPAL + ", " + ConstantesTelas
            .SUBTITULO_JANELA_CONFIG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Configuração Inicial - Banco de Dados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, -1, -1));

        jButtonOK.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButtonOK.setText("Salvar");
        jButtonOK.setName(ConstantesTelas.BTN_SALVAR_CONFIGURACAO);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 407, 97, -1));

        jButtonTestarConfiguracao.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButtonTestarConfiguracao.setText("Testar Configuração");
        jButtonTestarConfiguracao.setName(ConstantesTelas.BTN_TESTAR_CONFIGURACAO);
        jButtonTestarConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestarConfiguracaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTestarConfiguracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/database.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 0, -1, 269));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 18));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Host:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Usuário:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, 18));

        jPasswordFieldSenha.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jPasswordFieldSenha.setMaximumSize(new java.awt.Dimension(10, 28));
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 270, 40));

        jTextFieldHost.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        getContentPane().add(jTextFieldHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 270, 40));

        jTextFieldUser.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 270, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Porta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 18));

        jTextFieldPorta.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jTextFieldPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 270, 40));

        jTextFieldDatabase.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jTextFieldDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatabaseActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Base:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 18));

        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName(ConstantesTelas.BTN_CANCELAR);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 407, 97, -1));

        setSize(new java.awt.Dimension(650, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTestarConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestarConfiguracaoActionPerformed

    }//GEN-LAST:event_jButtonTestarConfiguracaoActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        //int opt = Mensagens.mostraMensagemPergunta(rootPane, "Tem certeza que deseja Salvar?");
//cancelar = 2
//ok = 0
//        try {
//            if (opt == 2) {
//Conf
//                c.setBanco(jTextFieldPorta.getText());
//                c.setIsPrimeiroAcesso(Boolean.FALSE);
//                c.setSenha(jPasswordFieldSenha.getText());
//                c.setUsuario(jTextFieldUser.getText());
//                c.setServidorPorta(jTextFieldPorta.getText());
//
//                ConfigUtils.atualizaArquivoConfiguracao(c);
//            }
//        } catch (IOException ex) {
//
//            Mensagens.mostraMensagemErro(rootPane, "Erro ao gravar configurações");
//
//        }

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jTextFieldPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPortaActionPerformed

    private void jTextFieldDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatabaseActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConfigInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConfigInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConfigInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConfigInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConfigInicialView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonTestarConfiguracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldDatabase;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldPorta;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

    private void removeListeners() {
        jButtonTestarConfiguracao.removeMouseListener(configInicialViewAction);
        jButtonCancelar.removeMouseListener(configInicialViewAction);
        jButtonOK.removeMouseListener(configInicialViewAction);
    }

    private void adicionaListeners() {
        jButtonTestarConfiguracao.addMouseListener(configInicialViewAction);
        jButtonCancelar.addMouseListener(configInicialViewAction);
        jButtonOK.addMouseListener(configInicialViewAction);
    }

    public Config getDadosAtualizar() {
        String senha = "";
        
        for (int i = 0; i < jPasswordFieldSenha.getPassword().length; i++) {
            senha += jPasswordFieldSenha.getPassword()[i];
        }

        Config c = new Config(Boolean.FALSE);
        c.setBanco(jTextFieldDatabase.getText());
        c.setIsPrimeiroAcesso(Boolean.FALSE);

        c.setSenha(senha);
        c.setUsuario(jTextFieldUser.getText());
        c.setHost(jTextFieldHost.getText());
        c.setServidorPorta(jTextFieldPorta.getText());

        return c;
    }
}
