/*
 * Copyright (C) 2016 fernando-pucci
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.etefgarcia.armarios.view;

import br.com.etefgarcia.armarios.action.TelaPrincipalViewAction;
import br.com.etefgarcia.armarios.controller.TelaPrincipalController;
import br.com.etefgarcia.armarios.model.Usuario;
import br.com.etefgarcia.armarios.util.constantes.telas.ConstantesTelas;

/**
 *
 * @author fernando-pucci
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    private TelaPrincipalController telaPrincipalController;
    private TelaPrincipalViewAction telaPrincipalViewAction;

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
        inicializar();
    }

    private void inicializar() {
        this.telaPrincipalController = new TelaPrincipalController();
        this.telaPrincipalViewAction = new TelaPrincipalViewAction(telaPrincipalController);

        removeListeners();
        adicionaListeners();

    }

    @Override
    public void dispose() {
        telaPrincipalController.getThreadConfirmarSaida().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new br.com.etefgarcia.armarios.model.Usuario();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelSuperior = new javax.swing.JPanel();
        jPanelBotoes = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelInferior = new javax.swing.JPanel();
        jLabelDadosUsuario = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemConfigurarBanco = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAlunos = new javax.swing.JMenu();
        jMenuItemConsultarAluno = new javax.swing.JMenuItem();
        jMenuItemCadastrarAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCarregarPlanilha = new javax.swing.JMenuItem();
        jMenuArmario = new javax.swing.JMenu();
        jMenuItemConsultarArmario = new javax.swing.JMenuItem();
        jMenuItemCadastrarArmario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConstantesTelas.TITULO_JANELA_PRINCIPAL + " " + ConstantesTelas.ETEC);
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        jPanelPrincipal.setLayout(new java.awt.GridLayout(5, 1));

        jPanelSuperior.setMaximumSize(new java.awt.Dimension(460, 80));
        jPanelSuperior.setMinimumSize(new java.awt.Dimension(460, 80));
        jPanelSuperior.setName(""); // NOI18N
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(460, 80));
        jPanelSuperior.setRequestFocusEnabled(false);
        jPanelSuperior.setLayout(new java.awt.GridLayout(2, 1));

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanelSuperior.add(jPanelBotoes);

        jPanelPrincipal.add(jPanelSuperior);
        jPanelPrincipal.add(filler3);
        jPanelPrincipal.add(filler2);
        jPanelPrincipal.add(filler4);

        jPanelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Usuário Logado:"));
        jPanelInferior.setPreferredSize(new java.awt.Dimension(500, 459));
        jPanelInferior.setLayout(new javax.swing.BoxLayout(jPanelInferior, javax.swing.BoxLayout.LINE_AXIS));

        jLabelDadosUsuario.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabelDadosUsuario.setText("jLabel1");
        jPanelInferior.add(jLabelDadosUsuario);

        jPanelPrincipal.add(jPanelInferior);

        jMenu.setMnemonic('s');
        jMenu.setText("Ações");
        jMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu.setName("acoes"); // NOI18N

        jMenuItemConfigurarBanco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemConfigurarBanco.setText("Configurar Banco de Dados");
        jMenuItemConfigurarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigurarBancoActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemConfigurarBanco);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.setName(ConstantesTelas.BTN_SAIR);
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSair);

        jMenuBar.add(jMenu);

        jMenuAlunos.setMnemonic('A');
        jMenuAlunos.setText("Alunos");
        jMenuAlunos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItemConsultarAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemConsultarAluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemConsultarAluno.setText("Buscar Alunos");
        jMenuItemConsultarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarAlunoActionPerformed(evt);
            }
        });
        jMenuAlunos.add(jMenuItemConsultarAluno);

        jMenuItemCadastrarAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadastrarAluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemCadastrarAluno.setText("Cadastrar Aluno");
        jMenuItemCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenuAlunos.add(jMenuItemCadastrarAluno);

        jSeparator1.setForeground(new java.awt.Color(30, 25, 25));
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 2));
        jMenuAlunos.add(jSeparator1);

        jMenuItemCarregarPlanilha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemCarregarPlanilha.setText("Carregar Planilha");
        jMenuItemCarregarPlanilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarregarPlanilhaActionPerformed(evt);
            }
        });
        jMenuAlunos.add(jMenuItemCarregarPlanilha);

        jMenuBar.add(jMenuAlunos);

        jMenuArmario.setMnemonic('m');
        jMenuArmario.setText("Armários");
        jMenuArmario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItemConsultarArmario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemConsultarArmario.setText("Consultar Armário");
        jMenuItemConsultarArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarArmarioActionPerformed(evt);
            }
        });
        jMenuArmario.add(jMenuItemConsultarArmario);

        jMenuItemCadastrarArmario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemCadastrarArmario.setText("Cadastrar Armário");
        jMenuItemCadastrarArmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarArmarioActionPerformed(evt);
            }
        });
        jMenuArmario.add(jMenuItemCadastrarArmario);

        jMenuBar.add(jMenuArmario);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(650, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed

        telaPrincipalController.getThreadConfirmarSaida().start();

    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAlunoActionPerformed

        telaPrincipalController.getThreadShowCadastrarAlunoView().start();

    }//GEN-LAST:event_jMenuItemCadastrarAlunoActionPerformed

    private void jMenuItemConfigurarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigurarBancoActionPerformed

        telaPrincipalController.getThreadShowConfigurarBancoView().start();

    }//GEN-LAST:event_jMenuItemConfigurarBancoActionPerformed

    private void jMenuItemConsultarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarAlunoActionPerformed

        telaPrincipalController.getThreadShowConsultarAlunoView().start();


    }//GEN-LAST:event_jMenuItemConsultarAlunoActionPerformed

    private void jMenuItemConsultarArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarArmarioActionPerformed

        telaPrincipalController.getThreadShowConsultarArmarioView().start();

    }//GEN-LAST:event_jMenuItemConsultarArmarioActionPerformed

    private void jMenuItemCadastrarArmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarArmarioActionPerformed

        telaPrincipalController.getThreadShowCadastrarArmarioView().start();

    }//GEN-LAST:event_jMenuItemCadastrarArmarioActionPerformed

    private void jMenuItemCarregarPlanilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarregarPlanilhaActionPerformed
        telaPrincipalController.getThreadShowCarregarPlanilhaAlunoView().start();
    }//GEN-LAST:event_jMenuItemCarregarPlanilhaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipalView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabelDadosUsuario;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenuAlunos;
    private javax.swing.JMenu jMenuArmario;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCadastrarAluno;
    private javax.swing.JMenuItem jMenuItemCadastrarArmario;
    private javax.swing.JMenuItem jMenuItemCarregarPlanilha;
    private javax.swing.JMenuItem jMenuItemConfigurarBanco;
    private javax.swing.JMenuItem jMenuItemConsultarAluno;
    private javax.swing.JMenuItem jMenuItemConsultarArmario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private br.com.etefgarcia.armarios.model.Usuario usuario;
    // End of variables declaration//GEN-END:variables

    private void removeListeners() {
        jMenuItemSair.removeMouseListener(telaPrincipalViewAction);
    }

    private void adicionaListeners() {

        jMenuItemSair.addMouseListener(telaPrincipalViewAction);
    }

    public javax.swing.JPanel getPainelInferior() {

        return this.jPanelInferior;
    }

    public void setUsuario(Usuario usuario) {

        this.usuario = usuario;

    }

    public Usuario getUsuario() {

        return this.usuario;

    }

    public void mostrarDadosUsuarioLogado() {

        this.jLabelDadosUsuario.setText(usuario.toString());

    }

}
