/*
 * Copyright (C) 2016 fernando-pucci
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package br.com.etefgarcia.armarios.view;

import br.com.etefgarcia.armarios.action.TelaPrincipalViewAction;
import br.com.etefgarcia.armarios.controller.TelaPrincipalController;
import br.com.etefgarcia.armarios.util.constantes.telas.ConstantesTelas;

/**
 *
 * @author fernando-pucci
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    private TelaPrincipalController telaPrincipalController;
    private TelaPrincipalViewAction telaPrincipalViewAction;

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
        inicializar();
    }

    private void inicializar() {
        this.telaPrincipalController = new TelaPrincipalController();
        this.telaPrincipalViewAction = new TelaPrincipalViewAction(telaPrincipalController);

        removeListeners();
        adicionaListeners();

    }

    @Override
    public void dispose() {
        telaPrincipalController.getThreadConfirmarSaida().start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelEsquerdo = new javax.swing.JPanel();
        jPanelBotoes = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemConfigurarBanco = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAlunos = new javax.swing.JMenu();
        jMenuItemCadastrarAluno = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConstantesTelas.TITULO_JANELA_PRINCIPAL + " " + ConstantesTelas.ETEC);
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        jPanelPrincipal.setLayout(new java.awt.GridBagLayout());

        jPanelEsquerdo.setPreferredSize(new java.awt.Dimension(500, 459));

        javax.swing.GroupLayout jPanelEsquerdoLayout = new javax.swing.GroupLayout(jPanelEsquerdo);
        jPanelEsquerdo.setLayout(jPanelEsquerdoLayout);
        jPanelEsquerdoLayout.setHorizontalGroup(
            jPanelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanelEsquerdoLayout.setVerticalGroup(
            jPanelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        jPanelPrincipal.add(jPanelEsquerdo, new java.awt.GridBagConstraints());

        jPanelBotoes.setMaximumSize(new java.awt.Dimension(100, 459));
        jPanelBotoes.setMinimumSize(new java.awt.Dimension(100, 459));
        jPanelBotoes.setName(""); // NOI18N
        jPanelBotoes.setPreferredSize(new java.awt.Dimension(100, 459));
        jPanelBotoes.setRequestFocusEnabled(false);
        jPanelBotoes.setLayout(new java.awt.GridLayout(5, 1));
        jPanelPrincipal.add(jPanelBotoes, new java.awt.GridBagConstraints());

        jMenu.setMnemonic('A');
        jMenu.setText("Ações");
        jMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu.setName("acoes"); // NOI18N

        jMenuItemConfigurarBanco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemConfigurarBanco.setText("Configurar Banco de Dados");
        jMenuItemConfigurarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigurarBancoActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemConfigurarBanco);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.setName(ConstantesTelas.BTN_SAIR);
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSair);

        jMenuBar.add(jMenu);

        jMenuAlunos.setText("Alunos");
        jMenuAlunos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItemCadastrarAluno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItemCadastrarAluno.setText("Cadastrar Aluno");
        jMenuItemCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenuAlunos.add(jMenuItemCadastrarAluno);

        jMenuBar.add(jMenuAlunos);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(650, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        telaPrincipalController.getThreadConfirmarSaida().start();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAlunoActionPerformed

        telaPrincipalController.getThreadShowCadastrarAlunoView().start();

    }//GEN-LAST:event_jMenuItemCadastrarAlunoActionPerformed

    private void jMenuItemConfigurarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigurarBancoActionPerformed
        telaPrincipalController.getThreadShowConfigurarBancoView().start();
    }//GEN-LAST:event_jMenuItemConfigurarBancoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPrincipalView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenuAlunos;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCadastrarAluno;
    private javax.swing.JMenuItem jMenuItemConfigurarBanco;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelEsquerdo;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables

    private void removeListeners() {
        jMenuItemSair.removeMouseListener(telaPrincipalViewAction);
    }

    private void adicionaListeners() {

        jMenuItemSair.addMouseListener(telaPrincipalViewAction);
    }
}
