--SCRIPT DE CRICAÇÃO DA BASE DE DADOS

--CREATE DATABASE CONTROLE_ARMARIOS_DEV;
--USE CONTROLE_ARMARIOS_DEV;
--DROP DATABASE CONTROLE_ARMARIOS_DEV;


--TABELA DE TESTES DE CONEXAO
CREATE TABLE DB_TESTE(

ID      BIGINT

);

INSERT INTO DB_TESTE VALUES (1);

--SELECT * FROM DB_TESTE;
--DROP TABLE DB_TESTE;

--TABELA LOOKUP TIPO USUARIO
CREATE TABLE LKP_TIPO_USUARIO(

ID_LKP_TIPO_USUARIO      BIGINT AUTO_INCREMENT NOT NULL,
DESCRICAO            VARCHAR(50),
FLG_ATIVO            BIT DEFAULT 1 NOT NULL,

PRIMARY KEY (ID_LKP_TIPO_USUARIO)

);
--SELECT * FROM LKP_TIPO_USUARIO;
--DROP TABLE LKP_TIPO_USUARIO;

--INSERCAO TABELA LOOKUP LKP_TIPO_USUARIO
INSERT INTO LKP_TIPO_USUARIO(DESCRICAO) VALUES('ADMINISTRADOR');
INSERT INTO LKP_TIPO_USUARIO(DESCRICAO) VALUES('BIBLIOTECA');
INSERT INTO LKP_TIPO_USUARIO(DESCRICAO) VALUES('PROFESSOR');
INSERT INTO LKP_TIPO_USUARIO(DESCRICAO) VALUES('OUTROS');

--SELECT * FROM LKP_TIPO_USUARIO;
--DROP TABLE LKP_TIPO_USUARIO;

--TABELA USUARIO
CREATE TABLE USUARIO(

ID_USUARIO          BIGINT AUTO_INCREMENT NOT NULL,
ID_LKP_TIPO_USUARIO BIGINT NOT NULL,
NOME                VARCHAR(100),
FLG_ATIVO           BIT DEFAULT 1 NOT NULL,

PRIMARY KEY (ID_USUARIO),
FOREIGN KEY (ID_LKP_TIPO_USUARIO) REFERENCES LKP_TIPO_USUARIO(ID_LKP_TIPO_USUARIO)

) ENGINE=InnoDB;

--SELECT * FROM USUARIO;
--DROP TABLE USUARIO;

--TABELA ALUNO
CREATE TABLE ALUNO(

ID_ALUNO      BIGINT AUTO_INCREMENT NOT NULL,
NOME          VARCHAR(100),
SEXO          CHAR(1),
TELEFONE      VARCHAR(50),
EMAIL         VARCHAR(50),
FLG_ATIVO     BIT DEFAULT 1 NOT NULL,

PRIMARY KEY (ID_ALUNO)

) ENGINE=InnoDB;

--SELECT * FROM ALUNO;
--DROP TABLE ALUNO;

--TABELA ARMARIO
CREATE TABLE ARMARIO(

ID_ARMARIO      BIGINT AUTO_INCREMENT NOT NULL,
CHAVE           BIGINT,
DESCRICAO       VARCHAR(25),
FLG_OCUPADO     BIT DEFAULT 0 NOT NULL,
FLG_ATIVO       BIT DEFAULT 1 NOT NULL,

PRIMARY KEY (ID_ARMARIO)

) ENGINE=InnoDB;

--SELECT * FROM ARMARIO;
--DROP TABLE ARMARIO;


--TABELA ALUGUEL
CREATE TABLE ALUGUEL_ARMARIO(

ID_ALUGUEL_ARMARIO      BIGINT AUTO_INCREMENT NOT NULL,
ID_ARMARIO              BIGINT NOT NULL,
ID_ALUNO                BIGINT NOT NULL,
ID_USUARIO_RESPONSAVEL  BIGINT NOT NULL,
DATA_ALUGUEL            DATE,
DATA_SUGERIDA_DEVOLUCAO DATE,
DATA_DEVOLUCAO          DATE,
DURACAO                 BIGINT DEFAULT 0,
FLG_DEVOLVIDO           BIT DEFAULT 0 NOT NULL,


PRIMARY KEY (ID_ALUGUEL_ARMARIO),
FOREIGN KEY (ID_ARMARIO) REFERENCES ARMARIO(ID_ARMARIO),
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO),
FOREIGN KEY (ID_USUARIO_RESPONSAVEL) REFERENCES USUARIO(ID_USUARIO)

) ENGINE=InnoDB;
--SELECT * FROM ALUGUEL_ARMARIO;
--DROP TABLE ALUGUEL_ARMARIO;
