--TRIGGER PARA DESALOCAR ARMARIO, AO ATUALIZAR TABELA DE ALUGUEL, COM DATA DEVOLUCAO
DELIMITER //
CREATE TRIGGER DESALOCAR_ARMARIO_TRG
AFTER UPDATE
   ON ALUGUEL_ARMARIO FOR EACH ROW

BEGIN

IF(NEW.FLG_DEVOLVIDO = 1) THEN
   UPDATE ARMARIO
   SET FLG_OCUPADO = 0
   WHERE ID_ARMARIO = NEW.ID_ARMARIO;
END IF;
END; //

DELIMITER;